Add support for nvme drives. Cuz disk /dev address is /dev/nvme0n1...(add the p for partitions)

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -201,7 +201,7 @@ chrooting() {
 
 	echo "copy_over_chroot" >> .progress
 
-	arch-chroot /mnt /linux-autoinstall/deploy-internal $disk0 $keyfilegrub $keypref || fatal "Arch-chroot."
+	arch-chroot /mnt /linux-autoinstall/deploy-internal $disk $disk0 $keyfilegrub $keypref || fatal "Arch-chroot."
 }
 
 ask_key_copy() {
@@ -308,6 +308,25 @@ get_passwd() {
 	done
 }
 
+get_disk() {
+	grep -q get_disk .progress &&
+	       log "Skipping disk information" &&
+	       return
+	get_data "Enter the disk that archlinux will be installed on (e.g. /dev/sdx) " disk
+
+	if [[ $disk0 == *"/dev/sd"* ]]; then
+		log "Got a /dev/sd* disk!!!"
+		disk0="${disk}"
+	elif [[ $disk0 == *"/dev/nvme"* ]]; then
+		log "Got a /dev/nvme* disk!!!"
+		disk0="${disk}p"
+	else
+		fatal "Invalid input... (we might not support a such a disk)"
+		exit 1
+	fi
+	echo "get_disk" >> .progress
+}
+
 stage1_install() {
 
 	log "Starting stage1 install..."
@@ -316,7 +335,8 @@ stage1_install() {
 	ask_get_mirrors
 
 	# get disk
-	get_data "Enter the disk that archlinux will be installed on (e.g. /dev/sdx) " disk0
+	#get_data "Enter the disk that archlinux will be installed on (e.g. /dev/sdx) " disk0
+	get_disk
 	consent
 
 	partition_disk
