fix get_disk and fdisk formatting command for nvme

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -44,13 +44,13 @@ partition_disk() {
 
 	# prep disks
 	log "Formatting disk"
-	fdisk "$disk0" << FDISK_CMDS_PREP || fatal "Format disks."
+	fdisk "$disk" << FDISK_CMDS_PREP || fatal "Format disks."
 g
 w
 FDISK_CMDS_PREP
 	
 	# start formatting disk
-	fdisk "$disk0" << FDISK_CMDS || fatal "Create partitions"
+	fdisk "$disk" << FDISK_CMDS || fatal "Create partitions"
 n
 1
 
@@ -309,21 +309,25 @@ get_passwd() {
 }
 
 get_disk() {
-	grep -q get_disk .progress &&
-	       log "Skipping disk information" &&
-	       return
+#	grep -q get_disk .progress &&
+#	       log "Skipping disk information" &&
+#	       return
 	get_data "Enter the disk that archlinux will be installed on (e.g. /dev/sdx) " disk
 
-	if [[ "$disk0" =~ ^/dev/sd.* ]]; then
-		log "Got a /dev/sd* disk!!!"
-		disk0="${disk}"
-	elif [[ "$disk0" =~ ^/dev/nvme.* ]]; then
-		log "Got a /dev/nvme* disk!!!"
-		disk0="${disk}p"
-	else
-		fatal "Invalid input... (we might not support a such a disk)"
-		exit 1
-	fi
+	case $disk in
+		*"sd"*)
+			log "Got a /dev/sd* disk!!!"
+			disk0="${disk}"
+			;;
+		*"nvme"*)
+			log "Got a /dev/nvme* disk!!!"
+			disk0="${disk}p"
+			;;
+		*)
+			fatal "Invalid input... (we might not support a such a disk)"
+			exit 1
+			;;
+	esac
 	echo "get_disk" >> .progress
 }
 
