Fix libxft clean deploy and deploy-internal

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -31,15 +31,15 @@ get_mirrors() {
 }
 
 partition_disk() {
-# prep disks
-log "Formatting disk"
-fdisk "$disk0" << FDISK_CMDS_PREP || fatal "Format disks."
+	# prep disks
+	log "Formatting disk"
+	fdisk "$disk0" << FDISK_CMDS_PREP || fatal "Format disks."
 g
 w
 FDISK_CMDS_PREP
-
-# start formatting disk
-fdisk "$disk0" << FDISK_CMDS || fatal "Create partitions"
+	
+	# start formatting disk
+	fdisk "$disk0" << FDISK_CMDS || fatal "Create partitions"
 n
 1
 
@@ -73,220 +73,219 @@ FDISK_CMDS
 }
 
 set_crypt() {
-log "Setting up cryptography"
-homekfile="/root/$(echo "$keypref")keyfile_home"
-dd if=/dev/urandom of="$homekfile" bs=1024 count=10 &&
-
-echo -e "$passroot" | cryptsetup luksFormat --hash=sha512 --key-size=512 --cipher=aes-xts-plain64 --type luks2 --iter-time=1000 $(echo "$disk0")3 &&
-echo -e "$passroot" | cryptsetup luksFormat --hash=sha512 --key-size=512 --cipher=aes-xts-plain64 --type luks2 --iter-time=1000 $(echo "$disk0")4 &&
-echo -e "$passroot" | cryptsetup luksAddKey $(echo "$disk0")4 "$homekfile" || fatal "Cryptsetup."
+	log "Setting up cryptography"
+	homekfile="/root/$(echo "$keypref")keyfile_home"
+	dd if=/dev/urandom of="$homekfile" bs=1024 count=10 &&
+	
+	echo -e "$passroot" | cryptsetup luksFormat --hash=sha512 --key-size=512 --cipher=aes-xts-plain64 --type luks2 --iter-time=1000 $(echo "$disk0")3 &&
+	echo -e "$passroot" | cryptsetup luksFormat --hash=sha512 --key-size=512 --cipher=aes-xts-plain64 --type luks2 --iter-time=1000 $(echo "$disk0")4 &&
+	echo -e "$passroot" | cryptsetup luksAddKey $(echo "$disk0")4 "$homekfile" || fatal "Cryptsetup."
 }
 
 copy_key_support() {
-log "Adding key copy support"
-rootkfile="/root/$(echo "$keypref")keyfile_root"
-dd if=/dev/urandom of="$rootkfile" bs=1024 count=10 &&
-echo -e "$passroot" | cryptsetup luksAddKey $(echo "$disk0")3 "$rootkfile" || fatal "Key copy support"
+	log "Adding key copy support"
+	rootkfile="/root/$(echo "$keypref")keyfile_root"
+	dd if=/dev/urandom of="$rootkfile" bs=1024 count=10 &&
+	echo -e "$passroot" | cryptsetup luksAddKey $(echo "$disk0")3 "$rootkfile" || fatal "Key copy support"
 }
 
 copy_key() {
-log "Copying key"
-mkdir /mnt0 &&
-mount "$usb" /mnt0 || fatal "Mount USB."
-if [ $(df -TH "$usb" | grep /dev | awk '{print $2}') != "ext4" ]
-then
-	log "The usb is not an ext4 formatted disk, or the disk isn't valid, the key file will not be copied!!" &&
-	keyfilegrub=""&&
-	umount /mnt0
-	rmdir /mnt0
-else
-	cp "$rootkfile" /mnt0/ &&
-	usbuuid=$(blkid | grep "usb" | awk '{print $2}' | sed 's/"//g') &&
-	umount /mnt0 &&
-	rmdir /mnt0 &&
-	keyfilegrub="$usbuuid:ext4:$(echo "$keypref")keyfile_root"
-fi
+	log "Copying key"
+	mkdir /mnt0 &&
+	mount "$usb" /mnt0 || fatal "Mount USB."
+	if [ $(df -TH "$usb" | grep /dev | awk '{print $2}') != "ext4" ]
+	then
+		log "The usb is not an ext4 formatted disk, or the disk isn't valid, the key file will not be copied!!" &&
+		keyfilegrub=""&&
+		umount /mnt0
+		rmdir /mnt0
+	else
+		cp "$rootkfile" /mnt0/ &&
+		usbuuid=$(blkid | grep "usb" | awk '{print $2}' | sed 's/"//g') &&
+		umount /mnt0 &&
+		rmdir /mnt0 &&
+		keyfilegrub="$usbuuid:ext4:$(echo "$keypref")keyfile_root" &&
+		log "Keyfile is successfully copied"|| fatal "Copy keyfile to usb"	
+	fi
 }
 
 unlock_crypt() {
-log "Decrypting partitions"
-echo -e "$passroot" | cryptsetup open $(echo "$disk0")3 cryptroot &&
-passroot="" &&
-cryptsetup open --key-file="$homekfile" $(echo "$disk0")4 crypthome || fatal "Unlocking partitions."
+	log "Decrypting partitions"
+	echo -e "$passroot" | cryptsetup open $(echo "$disk0")3 cryptroot &&
+	passroot="" &&
+	cryptsetup open --key-file="$homekfile" $(echo "$disk0")4 crypthome || fatal "Unlocking partitions."
 }
 
 format_partitions() {
-log "Formatting partitions"
-mkfs.ext4 /dev/mapper/cryptroot &&
-mkfs.ext4 /dev/mapper/crypthome &&
-mkfs.ext4 $(echo "$disk0")2 || fatal "Formatting partitions."
+	log "Formatting partitions"
+	mkfs.ext4 /dev/mapper/cryptroot &&
+	mkfs.ext4 /dev/mapper/crypthome &&
+	mkfs.ext4 $(echo "$disk0")2 || fatal "Formatting partitions."
 }
 
 mount_partitions() {
-log "Mounting partitions"
-mount /dev/mapper/cryptroot /mnt &&
-mkdir /mnt/boot &&
-mkdir /mnt/home &&
-mount $(echo "$disk0")2 /mnt/boot &&
-mount /dev/mapper/crypthome /mnt/home || fatal "Mounting partitions."
+	log "Mounting partitions"
+	mount /dev/mapper/cryptroot /mnt &&
+	mkdir /mnt/boot &&
+	mkdir /mnt/home &&
+	mount $(echo "$disk0")2 /mnt/boot &&
+	mount /dev/mapper/crypthome /mnt/home || fatal "Mounting partitions."
 }
 
 pacstrapping() {
-log "Pacstrapping"
-pacstrap /mnt base linux linux-firmware linux-hardened || fatal "Packstrapping."
+	log "Pacstrapping"
+	pacstrap /mnt base linux linux-firmware linux-hardened || fatal "Packstrapping."
 }
 
 chrooting() {
-log "Chrooting"
-cp -R ../linux-autoinstall /mnt/linux-autoinstall &&
-cp "$homekfile" /mnt/ || fatal "Copy linux-autoinstall and home key."
-arch-chroot /mnt /linux-autoinstall/deploy-internal $disk0 $keyfilegrub $keypref || fatal "Arch-chroot."
+	log "Chrooting"
+	cp -R ../linux-autoinstall /mnt/linux-autoinstall &&
+	cp "$homekfile" /mnt/ || fatal "Copy linux-autoinstall and home key."
+	arch-chroot /mnt /linux-autoinstall/deploy-internal $disk0 $keyfilegrub $keypref || fatal "Arch-chroot."
 }
 
 ask_key_copy() {
-while true
-do
-	read -r -p "Do you want to copy keyfiles to usb for automatic crypto? [Yes/No] " yn
-
-	case $yn in
-	    Yes )
-			log "Yes"
-			log "Started the copying process"
-			copy_key_support
-			copy_key
-			# get usb
-			log "Sleeping for 10 seconds, insert the USB you wish to copy your keyfile to..."
-			sleep 10
-			lsblk
-			get_data "Enter the usb partition for the keyfile:" usb
-			break
+	while true
+	do
+		read -r -p "Do you want to copy keyfiles to usb for automatic crypto? [Yes/No] " input
+	
+		case $input in
+		    [yY][eE][sS]|[yY])
+				log "Yes"
+				log "Started the copying process"
+				copy_key_support
+				copy_key
+				# get usb
+				log "Sleeping for 10 seconds, insert the USB you wish to copy your keyfile to..."
+				sleep 10
+				lsblk
+				get_data "Enter the usb partition for the keyfile:" usb
+				break
+				;;
+		    [nN][oO]|[nN])
+				log "No"
+				log "Terminated the copying process"
+				break
+		    ;;
+		    *)
+			echo 'Invalid input...'
 			;;
-	    No )
-			log "No"
-			log "Terminated the copying process"
-			break
-	    ;;
-	    *)
-		echo 'Invalid input... Type "Yes" or "No"'
-		;;
-	esac
-done
-
+		esac
+	done
 }
 
 ask_get_mirrors() {
-while true
-do
-	read -r -p "Do you want to set up optimal mirrors? Or set them up manually? This might take a long time. [Yes/Set/No] " yn
-
-	case $yn in
-	    Yes )
-			log "Getting mirrors"
-			get_mirrors >/dev/null 2>&1
-			break
+	while true
+	do
+		read -r -p "Do you want to set up optimal mirrors? Or set them up manually? This might take a long time. [Yes/Set/No] " input
+	
+		case $input in
+		    [yY][eE][sS]|[yY])
+				log "Getting mirrors"
+				get_mirrors >/dev/null 2>&1
+				break
+				;;
+				[sS][eE][tT]|[s])
+				log "Setting up mirorrs"
+				vim /etc/pacman.d/mirrorlist
+				break
+				;;
+		    [nN][oO]|[nN])
+				log "Not setting up mirrors."
+				log "The default ones are going to be used."
+				break
+		    ;;
+		    *)
+			echo 'Invalid input...'
 			;;
-			Set )
-			log "Setting up mirorrs"
-			vim /etc/pacman.d/mirrorlist
-			break
-			;;
-	    No )
-			log "Not setting up mirrors."
-			log "The default ones are going to be used."
-			break
-	    ;;
-	    *)
-		echo 'Invalid input... Type "Yes", "Set" or "No"'
-		;;
-	esac
-done
-
+		esac
+	done
 }
 
 consent() {
-while true
-do
-	read -r -p "Are you sure you want to install archlinux in disk $disk0? All contents of the disk will be WIPED [Yes/No] " yn
-
-	case $yn in
-	    Yes )
-			echo "Yes"
-			log "Proceding"
-			break
+	while true
+	do
+		read -r -p "Are you sure you want to install archlinux in disk $disk0? All contents of the disk will be WIPED [Yes/No] " input
+	
+		case $input in
+		    Yes)
+				echo "Yes"
+				log "Proceding"
+				break
+				;;
+		    No)
+				echo "No"
+				fatal "You have terminated the script!!!"
+				exit 1
+		    ;;
+		    *)
+			echo 'Invalid input... Type "Yes" or "No"'
 			;;
-	    No )
-			echo "No"
-			fatal "You have terminated the script!!!"
-			exit 1
-	       		;;
-	    *)
-		echo 'Invalid input... Type "Yes" or "No"'
-		;;
-	esac
-done
+		esac
+	done
 }
 
 get_data() {
-read -r -p "$1" "$2" || fatal "Invalid input."
+	read -r -p "$1" "$2" || fatal "Invalid input."
 }
 
 get_passwd() {
-while true
-do
-	read -r -s -p "Enter a password for cryptography:" passroot &&
-	echo ""
-	read -r -s -p "Repeat the password for cryptography:" passrootrpt &&
-	echo ""
-	if [ "$passroot" == "$passrootrpt" ]
-	then
-		log "Passwords match, proceeding"
-		passrootrpt="" || fatal "Error with password setup"
-		break
-	else
-		log "${color_fatal} Passwords don't match, try again"
-		continue
-	fi
-done
+	while true
+	do
+		read -r -s -p "Enter a password for cryptography:" passroot &&
+		echo ""
+		read -r -s -p "Repeat the password for cryptography:" passrootrpt &&
+		echo ""
+		if [ "$passroot" == "$passrootrpt" ]
+		then
+			log "Passwords match, proceeding"
+			passrootrpt="" || fatal "Error with password setup"
+			break
+		else
+			log "${color_fatal} Passwords don't match, try again"
+			continue
+		fi
+	done
 }
 
 stage1_install() {
 
-log "Starting stage1 install..."
+	log "Starting stage1 install..."
 
-check_inet
-ask_get_mirrors
+	check_inet
+	ask_get_mirrors
 
-# get disk
-get_data "Enter the disk that archlinux will be installed on (e.g. /dev/sdx) " disk0
-# get sizes
-get_data "Enter the size of the root partition (the swap file will be stored here)-(for fdisk) " rootsize
-get_data "Enter the size of the home partition (for fdisk) " homesize
+	# get disk
+	get_data "Enter the disk that archlinux will be installed on (e.g. /dev/sdx) " disk0
+	# get sizes
+	get_data "Enter the size of the root partition (the swap file will be stored here)-(for fdisk) " rootsize
+	get_data "Enter the size of the home partition (for fdisk) " homesize
 
-consent
+	consent
 
-partition_disk
+	partition_disk
 
-# get crypt
-get_passwd
-# get keypref
-get_data "We will create keyfiles for your new system, if you want to prefix your new keyfiles with some string, so that the script does not overwrite your old keys, enter this string:" keypref
+	# get crypt
+	get_passwd
+	# get keypref
+	get_data "We will create keyfiles for your new system, if you want to prefix your new keyfiles with some string, so that the script does not overwrite your old keys, enter this string:" keypref
 
-set_crypt
+	set_crypt
 
-# copy key file support
-keyfilegrub=""
-ask_key_copy
+	# copy key file support
+	keyfilegrub=""
 
-unlock_crypt
+	ask_key_copy
 
-format_partitions
+	unlock_crypt
 
-mount_partitions
+	format_partitions
 
-pacstrapping
+	mount_partitions
 
-chrooting
+	pacstrapping
 
+	chrooting
 }
 
 stage1_install
